# Generated by Django 6.0.3 on 2026-03-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamland_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
