# Generated by Django 6.0.3 on 2026-03-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamland_app', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
