# Generated by Django 6.0.3 on 2026-03-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamland_app', '0006_feedback_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
