# Generated by Django 6.0.3 on 2026-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamland_app', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='route',
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('Train', 'Train'), ('Flight', 'Flight'), ('Bus', 'Bus')], max_length=20),
        ),
    ]
